### ISSUE TITLE
ios 集成有问题，是否帮忙看一下，多谢。

### ISSUE THREAD

**Issue by zhiming137** [xiaozhicheng/react-native-pay#3] opened 2017-04-24 14:57 UTC
Libtool /Users/mars/workspace/biqu/react-native-cinema-app/ios/build/Build/Products/Debug-iphonesimulator/libReactNativePay.a normal x86_64
    cd /Users/mars/workspace/biqu/react-native-cinema-app/node_modules/react-native-paysdk/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/mars/.nvm/versions/node/v7.7.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/mars/Library/Android/sdk/tools:/Users/mars/Library/Android/sdk/platform-tools:/Applications/Redis.app/Contents/Resources/Vendor/redis/bin:/Users/mars/Documents/workspace/phacility/arcanist/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -L/Users/mars/workspace/biqu/react-native-cinema-app/ios/build/Build/Products/Debug-iphonesimulator -L/Users/mars/workspace/biqu/react-native-cinema-app/node_modules/react-native-paysdk/ios/PaySdk/微信 -filelist /Users/mars/workspace/biqu/react-native-cinema-app/ios/build/Build/Intermediates/ReactNativePay.build/Debug-iphonesimulator/ReactNativePay.build/Objects-normal/x86_64/ReactNativePay.LinkFileList /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libz.tbd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libc++.tbd -framework CoreMotion -framework CFNetwork -framework Foundation -framework UIKit -framework CoreGraphics -framework CoreText -framework QuartzCore -framework CoreTelephony -framework SystemConfiguration /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libsqlite3.tbd -lWeChatSDK -framework AlipaySDK -o /Users/mars/workspace/biqu/react-native-cinema-app/ios/build/Build/Products/Debug-iphonesimulator/libReactNativePay.a

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libz.tbd (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libc++.tbd (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/libsqlite3.tbd (No such file or directory)

** BUILD FAILED **

The following build commands failed:
	Libtool /Users/mars/workspace/biqu/react-native-cinema-app/ios/build/Build/Products/Debug-iphonesimulator/libReactNativePay.a normal x86_64
(1 failure)

**Comment by h31639347** [comment] 2017-04-28 01:11
也遇到这个问题，没做过ios。。。

**Comment by AlexanderYao** [comment] 2017-08-15 02:09
Duplicate of #4

**Closed as completed** 2017-09-07 08:08 UTC
